### ISSUE TITLE
Uncontrolled build up of buffers in HttpPostEmitter

### ISSUE THREAD

**Issue by xanec** [metamx/java-util#65]
Currently, in `HttpPostEmitter`, when a `Batch` object is sealed, it will call `onSealExclusive` in `HttpPostEmitter`:
https://github.com/metamx/java-util/blob/8eafafb7831c699410de9ada555252bfb2afdd03/src/main/java/com/metamx/emitter/core/HttpPostEmitter.java#L250-L261

Notice that this will automatically create a new `Batch` object as the `concurrentBatch`. What this may result, and what we have observed, is that there may be an uncontrolled build up of these objects especially when the `EmittingThread` does not emit fast enough and result in OOME.

Without altering the existing behavior (e.g., additional block elsewhere in the code), I suggest that we can put in additional checks on queue length in `emitAndReturnBatch`:
https://github.com/metamx/java-util/blob/8eafafb7831c699410de9ada555252bfb2afdd03/src/main/java/com/metamx/emitter/core/HttpPostEmitter.java#L216-L227

While this is not strictly and directly linked to the queue but it should allow some degree of control in the queue length (i.e., not adding new events to the `Batch` when there are already plenty to clear) and at the same, the blocking is expected in this method call.

**Comment by leventov** [comment]
@xanec instead of rejecting new events, I suggest to gradually drop batches from the `failedBuffers` queue, e. g. if there are three consecutive failures of the same buffer to be emitted. I. e. focus changes around `tryEmitOneFailedBuffer()` method. Also, according to https://github.com/druid-io/druid/pull/4973#issuecomment-338282140, I think we should change `emitter/buffers/allocated` metric from delta to gauge.
